[store]
[store.primary]
connection = "postgresql://ag-node:antigravity@postgres-sepolia:5432/ag-node"
weight = 1
pool_size = 10
[store.base_sepolia]
connection = "postgresql://ag-node:antigravity@postgres-base-sepolia:5432/ag-node"
weight = 1
pool_size = 10
[chains]
ingestor = "graph-node"
[chains.sepolia]
shard = "primary"
provider = [ { label = "sepolia", url = "https://eth-sepolia.g.alchemy.com/v2/RvG1g8xHiynLMuESOdK0U0-onioZUK9l", features = [] } ]

[chains.base-sepolia]
shard = "base_sepolia"
provider = [ { label = "base-sepolia", url = "https://base-sepolia.g.alchemy.com/v2/RvG1g8xHiynLMuESOdK0U0-onioZUK9l", features = [] } ]

[deployment]
[[deployment.rule]]
match = { network = [ "sepolia", "base-sepolia"] }
indexers = [ "graph-node" ]
[[deployment.rule]]
indexers = [ "graph-node" ]